### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by zsup** [spark/mobile-sdk-ios#39]
Just did a comprehensive review of the app to pull together a list of UI tweaks. Overall I'd say we're about 75% there; it needs a bunch of clean-up and polish, but the structure's there.

There are a few places where this diverges significantly from the spec (entire views are missing and replaced with pop ups), and I think what's done here is more confusing and more difficult to use. I'd like to see a flow that is more like what's described in the "Spark Mobile SDK Views" Google Doc.

Overall I saw a few patterns that should be fixed throughout the app:
- In general we want more whitespace to make the whole thing feel simpler and easier to follow
- Elements should be better centered, both horizontally and vertically
- Text should be a little bigger so it's more readable, and should use the custom font throughout
- We should avoid jargony terms like "SSID" that most people don't know, and instead use English. We should also use full sentences with punctuation rather than shorthand, which feels unprofessional to me. Tell a story instead of giving a list!

Here are a bunch of specific fixes:

Flash screen
- [x] Should this exist?
- [x] Button at the bottom should be ~10px taller
- [x] Text in the button is not properly vertically centered
- [x] Version number in the bottom corner should use the custom font
- [x] The button should be 10% darkened when tapped

Create account
- [x] Increase spacing both above and below the logo in the top section (but a bit more above)
- [x] "Create {company} account" should also bolded like a header
- [x] Text boxes should be vertically centered on the screen
- [x] When I type in the text boxes, the text is aligned all the way to the left; it should be spaced out better (like the placeholder text is)
- [x] I already have an account should be underlined but not bolded; will help it look like a link
- [x] Text at the bottom should be aligned to the bottom of the screen
- [x] All text should be in the custom font
- [x] The button should be 10% darkened when tapped
- [x] Clicking away from the text boxes should make the keyboard go away

Login
- [x] "Login" should be bolded like a header and spaced like a header (closer to the top)
- [x] Same general spacing and formatting changes from the previous screen
- [x] After I hit 'Log in' the 'create account' view pops up for just a moment
- [x] All text should be in the custom font

Get Ready
- [x] Where is this page? Need to add it. There should be instructions for preparing the hardware before the user gets to the instructions they need to follow on the phone.

Set up instructions
- [x] This page has diverged a lot from the spec, which was a lot simpler. This page is confusing. We need to eliminate content and make this more visual.
- [x] Device icon should be spaced further from the topic
- [x] This view has too much content on it, and so it's confusing. All of the 'troubleshooting' content should move on to the previous 'Get Ready' page, so this page should just be instructions (which should then be larger and more spaced out, whitespace please!)

- [x] Take off the spinner, which is confusing here (because it makes the user think they should be just sitting around waiting for something to happen)
- [ ] The 'log out' and 'cancel' buttons at the bottom in the same color are a bit confusing. can we make them two different colors?
- [x] All text should be in the custom font
- [x] In general, please revert the design of this page to better align with the spec: https://docs.google.com/a/spark.io/presentation/d/1WrIhPIoY2keRxlKurJDsF02_dAq8w5Zys0URCHsTwPE/edit#slide=id.g5539d65f3_017

Select network
- [x] More whitespace around everything. Make the scrolling box smaller in exchange for more space around all of the elements.
- [x] Heading at the beginning should be a larger font
- [x] All text should be in the custom font
- [x] Icons aren't rendering cleanly (they're jagged, not smooth curves)
- [x] Sort networks alphabetically. I think. actually I'd love feedback on this, I find the current order confusing, and my Mac laptop sorts networks alphabetically, which feels like it makes sense to me
- [ ] Multiple networks with the same SSID should be eliminated. You should only see one of each
- [x] The scrolling box needs something around it to show that it's scrollable; a border or a background or something to separate it from the rest of the screen
- [x] Button text should be bolded
- [x] "Manual SSID" should instead say "Type network name manually"
- [ ] Also, "Manual SSID" should actually do something :-)
- [x] Scrolling box should be horizontally centered (it's too far to the right)

Connect to Network
- [x] Doesn't exist at all, instead replaced by a pop-up. I don't like the pop-up because it doesn't provide us the option to make the Wi-Fi password unobscured (which will reduce fat finger issues). Let's make this its own view.

Connecting
- [x] More whitespace around the whole top section
- [x] Add punctuation to the top section (connecting to: and "This can take about a minute.")
- [x] There shouldn't be a separate background on the checkboxes section, and the horizontal lines also feel like they're spaced wrong and shouldn't exist at all
- [ ] Spinners should be smaller so they're not bigger than the check marks
- [x] Error message for a failed connection should be in English. "Claiming" a device does not mean anything to the end user. In fact the error message shouldn't exist at all, and should be replaced by the view below.

Connection Failed
- [x] Where is this view? Replaced with an error message, which is too brief and confusing. Please build out the view instead.

Success
- [x] Unfortunately never saw it! Got an error message instead. Looking forward to seeing it though :-)

**Comment by idokleinman** [comment]
This issue was moved to spark/spark-setup-ios#11
