### ISSUE TITLE
Sign up fails with non-descriptive error message

### ISSUE THREAD

**Issue by emilyrose** [spark/mobile-sdk-ios#40]
Steps to reproduce:

1. Populate sign-up form with:
    * email: __nexxy@spark.io__
    * password: __12345678__
1. Tap 'sign up' button

The resulting popup reads:
````
Error
Could not sign up
````

This issue may just primarily serve as a reminder to add more descriptive error messages.

__the actual cause of this error is that my email address has already been associated with a "teacup" account (I did not realize this at the time).__

**Comment by idokleinman** [comment]
This issue was moved to spark/spark-setup-ios#18
