### ISSUE TITLE
Document soft AP device command flow

### ISSUE THREAD

**Issue by towynlin** [spark/mobile-sdk-ios#41]
I'm imagining this to simply be a code comment somewhere, but it could be in the README or another piece of documentation. It would help newcomers to the code get oriented if there were a list of the typical flow through soft AP in terms of the commands issued to the device.

From a conversation with @idokleinman, here's the current state of things:

> device-id -> public-key -> set -> scan-ap -> configure-ap -> connect-ap

**Comment by idokleinman** [comment]
This issue was moved to spark/spark-setup-ios#20

**Comment by idokleinman** [comment]
This issue was moved to spark/spark-setup-ios#21
