### ISSUE TITLE
Org vs non-org API endpoints

### ISSUE THREAD

**Issue by towynlin** [spark/mobile-sdk-ios#59]
Three endpoints are the same regardless of whether the app is for an organization.

- Login: `POST /oauth/token`
- Create claim code: `POST /v1/device_claims` _(as of Feb 24, need to fix in app & API)_
- List devices: `GET /v1/devices`

However, one API endpoint will be different between a generic Spark user context and in the context of an organization.

### User Sign Up

Conceptually, is the user signing up for a Spark account or to be a customer of the other organization?

For an organization:

    POST /v1/orgs/mycompany/customers

    email=test@mycompany.com&password=7he$ecret

For generic Spark users:

    POST /v1/users

    username=test@mycompany.com&password=7he$ecret

**Comment by idokleinman** [comment]
This issue was moved to spark/spark-setup-ios#5

**Comment by idokleinman** [comment]
This issue was moved to spark/spark-setup-ios#7
